Apply lossy_provenance_casts lint
```

error: under strict provenance it is considered bad style to cast pointer `*mut core::ffi::c_void` to integer `usize`
   --> src/sys/reg.rs:168:9
    |
168 |         self.0 as usize
    |         ^^^^^^---------
    |               |
    |               help: use `.addr()` to obtain the address of a pointer: `.addr()`
    |
    = help: if you can't comply with strict provenance and need to expose the pointer provenance you can use `.expose_provenance()` instead
    = note: requested on the command line with `-D lossy-provenance-casts`
```