tests: Update mips target specs
```
+ RUSTFLAGS='-D warnings -C link-arg=-Tlink.x -A linker_messages' \
+ cargo run --target /home/runner/work/semihosting/semihosting/target-specs/mips-unknown-none.json -Z json-target-spec --features qemu-system -Z build-std=core -- a '' 'c d'
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -D warnings -C link-arg=-Tlink.x -A linker_messages --target /home/runner/work/semihosting/semihosting/target-specs/mips-unknown-none.json -Zunstable-options --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg -Wwarnings` (exit status: 1)
  --- stderr
  error: error loading target specification: invalid MIPS ABI name and `cfg(target_abi)` combination:
         ABI name:
         cfg(target_abi):
    |
    = help: run `rustc --print target-list` for a list of built-in targets
```