ci: Pin cortex-m-rt in no-std test on Rust 1.64/1.83
```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rt-macros-0.7.6/Cargo.toml`

Caused by:
  `resolver` setting `3` is not valid, valid options are "1" or "2"
```